Repository TodayHouse/TodayHouse-Backend, pull requests merged in 2022-07, with the labels that each got.

#98 Ci Cd 설정
  .github/workflows/gradle.yml
  appspec.yml
  scripts/start.sh
Labels: :building_construction: 인프라

#99 스크랩북 기능 구현
  src/main/java/com/todayhouse/domain/scrap/api/ScrapController.java
  src/main/java/com/todayhouse/domain/scrap/application/ScrapService.java
  src/main/java/com/todayhouse/domain/scrap/application/ScrapServiceImpl.java
  src/main/java/com/todayhouse/domain/scrap/dao/CustomScrapRepository.java
  src/main/java/com/todayhouse/domain/scrap/dao/ScrapRepository.java
  src/main/java/com/todayhouse/domain/scrap/dao/ScrapRepositoryImpl.java
  src/main/java/com/todayhouse/domain/scrap/domain/Scrap.java
  src/main/java/com/todayhouse/domain/scrap/exception/ScrapExistException.java
  src/main/java/com/todayhouse/domain/scrap/exception/ScrapNotFoundException.java
  src/main/java/com/todayhouse/domain/story/api/StoryController.java
  src/main/java/com/todayhouse/domain/story/application/StoryService.java
  src/main/java/com/todayhouse/domain/story/application/StoryServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dao/CustomStoryRepositoryImpl.java
  src/main/java/com/todayhouse/domain/story/dao/StoryRepository.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetListResponse.java
  src/main/java/com/todayhouse/global/config/WebSecurityConfig.java
  src/main/java/com/todayhouse/global/error/BaseResponseStatus.java
  src/test/java/com/todayhouse/domain/scrap/api/ScrapControllerTest.java
  src/test/java/com/todayhouse/domain/scrap/application/ScrapServiceImplTest.java
  src/test/java/com/todayhouse/domain/scrap/dao/ScrapRepositoryTest.java
  src/test/java/com/todayhouse/domain/story/api/StoryControllerTest.java
  src/test/java/com/todayhouse/domain/story/application/StoryServiceImplTest.java
  src/test/java/com/todayhouse/domain/story/dao/StoryRepositoryTest.java
Labels: 🕹 기능, :hammer_and_wrench: 리팩토링

#102 cicd 스크립트 경로 수정
  scripts/start.sh
Labels: :building_construction: 인프라, :hammer_and_wrench: 리팩토링

#103 cicd 파일 스크립트 수정
  .github/workflows/gradle.yml
  scripts/start.sh
Labels: :building_construction: 인프라, :hammer_and_wrench: 리팩토링

#104 cicd 스크립트 경로 수정
  .github/workflows/gradle.yml
  scripts/start.sh
Labels: :building_construction: 인프라, :gear: 설정

#112 스토리 조회수 기능 구현
  src/main/java/com/todayhouse/domain/image/dao/StoryImageRepository.java
  src/main/java/com/todayhouse/domain/story/application/StoryServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dao/CustomStoryRepositoryImpl.java
  src/main/java/com/todayhouse/domain/story/dao/StoryRepository.java
  src/main/java/com/todayhouse/domain/story/domain/Story.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetDetailResponse.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetListResponse.java
  src/main/java/com/todayhouse/global/config/cookie/CookieUtils.java
  src/test/java/com/todayhouse/domain/story/api/StoryControllerTest.java
  src/test/java/com/todayhouse/domain/story/application/StoryServiceImplTest.java
Labels: 🕹 기능

#113 스토리에 유저 프로필 조회
  src/main/java/com/todayhouse/domain/story/application/StoryServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dao/StoryRepository.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetDetailResponse.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetListResponse.java
  src/test/java/com/todayhouse/domain/inquiry/api/InquiryControllerTest.java
  src/test/java/com/todayhouse/domain/inquiry/dao/InquiryRepositoryTest.java
  src/test/java/com/todayhouse/domain/product/application/ProductServiceImplTest.java
  src/test/java/com/todayhouse/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/todayhouse/domain/review/api/ReviewControllerTest.java
  src/test/java/com/todayhouse/domain/review/dao/ReviewRepositoryTest.java
  src/test/java/com/todayhouse/domain/scrap/api/ScrapControllerTest.java
Labels: 🕹 기능, :hammer_and_wrench: 리팩토링

#115 리뷰 이미지, 작성일 조회 추가
  src/main/java/com/todayhouse/domain/review/dto/response/ReviewResponse.java
  src/test/java/com/todayhouse/domain/review/api/ReviewControllerTest.java
Labels: 🕹 기능

#116 Story api 기능 수정
  src/main/java/com/todayhouse/domain/story/api/StoryReplyController.java
  src/main/java/com/todayhouse/domain/story/application/StoryReplyService.java
  src/main/java/com/todayhouse/domain/story/application/StoryReplyServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dto/reqeust/ReplyDeleteRequest.java
  src/main/java/com/todayhouse/domain/story/dto/response/ReplyGetResponse.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetDetailResponse.java
  src/test/java/com/todayhouse/domain/story/api/StoryControllerTest.java
Labels: :hammer_and_wrench: 리팩토링

#120 상품 조회 시 orderId 조회
  src/main/java/com/todayhouse/domain/order/application/OrderService.java
  src/main/java/com/todayhouse/domain/order/application/OrderServiceImpl.java
  src/main/java/com/todayhouse/domain/order/dao/OrderRepository.java
  src/main/java/com/todayhouse/domain/product/api/ProductController.java
  src/main/java/com/todayhouse/domain/product/dto/response/ProductResponse.java
  src/test/java/com/todayhouse/domain/order/application/OrdersServiceImplTest.java
  src/test/java/com/todayhouse/domain/product/api/ProductControllerTest.java
Labels: :hammer_and_wrench: 리팩토링
