Repository TodayHouse/TodayHouse-Backend, pull requests merged in 2022-03, with the labels that each got.

#43 :sparkles: 스토리, 노하우 CRU 기능 추가 (#21)
  build.gradle
  src/main/java/com/todayhouse/domain/image/api/ImageController.java
  src/main/java/com/todayhouse/domain/image/application/ImageService.java
  src/main/java/com/todayhouse/domain/image/application/ImageServiceImpl.java
  src/main/java/com/todayhouse/domain/image/dao/ImageRepository.java
  src/main/java/com/todayhouse/domain/image/domain/Image.java
  src/main/java/com/todayhouse/domain/story/api/StoryController.java
  src/main/java/com/todayhouse/domain/story/application/StoryService.java
  src/main/java/com/todayhouse/domain/story/application/StoryServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dao/StoryRepository.java
  src/main/java/com/todayhouse/domain/story/domain/Story.java
  src/main/java/com/todayhouse/domain/story/dto/reqeust/StoryCreateRequest.java
  src/main/java/com/todayhouse/domain/story/dto/reqeust/StoryUpdateRequest.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetDetailResponse.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetListResponse.java
  src/main/java/com/todayhouse/domain/story/exception/StoryNotFoundException.java
  src/main/java/com/todayhouse/global/common/BaseTimeEntity.java
  src/main/java/com/todayhouse/global/config/WebSecurityConfig.java
  src/main/java/com/todayhouse/global/error/BaseResponseStatus.java
  src/main/java/com/todayhouse/infra/S3Storage/controller/S3Controller.java
  src/main/java/com/todayhouse/infra/S3Storage/exception/InvalidFileExtensionException.java
  src/main/java/com/todayhouse/infra/S3Storage/service/FileService.java
  src/main/java/com/todayhouse/infra/S3Storage/service/FileServiceImpl.java
  src/main/java/com/todayhouse/infra/S3Storage/service/S3Service.java
  src/main/resources/application.yml
Labels: 🕹 기능

#46 Product option 기능 구현
  src/main/java/com/todayhouse/domain/product/api/OptionController.java
  src/main/java/com/todayhouse/domain/product/api/ProductController.java
  src/main/java/com/todayhouse/domain/product/application/OptionService.java
  src/main/java/com/todayhouse/domain/product/application/OptionServiceImpl.java
  src/main/java/com/todayhouse/domain/product/application/ProductServiceImpl.java
  src/main/java/com/todayhouse/domain/product/dao/ChildOptionRepository.java
  src/main/java/com/todayhouse/domain/product/dao/CustomProductRepository.java
  src/main/java/com/todayhouse/domain/product/dao/ParentOptionRepository.java
  src/main/java/com/todayhouse/domain/product/dao/ProductRepository.java
  src/main/java/com/todayhouse/domain/product/dao/ProductRepositoryImpl.java
  src/main/java/com/todayhouse/domain/product/dao/SelectionOptionRepository.java
  src/main/java/com/todayhouse/domain/product/domain/ChildOption.java
  src/main/java/com/todayhouse/domain/product/domain/ParentOption.java
  src/main/java/com/todayhouse/domain/product/domain/Product.java
  src/main/java/com/todayhouse/domain/product/domain/SelectionOption.java
  src/main/java/com/todayhouse/domain/product/dto/request/ChildOptionSaveRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ChildOptionUpdateRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ParentOptionSaveRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ParentOptionUpdateRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ProductSaveRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/ProductUpdateRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/SelectionOptionSaveRequest.java
  src/main/java/com/todayhouse/domain/product/dto/request/SelectionOptionUpdateRequest.java
  src/main/java/com/todayhouse/domain/product/dto/response/ChildOptionResponse.java
  src/main/java/com/todayhouse/domain/product/dto/response/ParentOptionResponse.java
  src/main/java/com/todayhouse/domain/product/dto/response/ProductResponse.java
  src/main/java/com/todayhouse/domain/product/dto/response/ProductSaveResponse.java
  src/main/java/com/todayhouse/domain/product/dto/response/SelectionOptionResponse.java
  src/main/java/com/todayhouse/domain/product/exception/ChildOptionNotFoundException.java
  src/main/java/com/todayhouse/domain/product/exception/OptionExistException.java
  src/main/java/com/todayhouse/domain/product/exception/ParentOptionNotFoundException.java
  src/main/java/com/todayhouse/domain/product/exception/ProductExistException.java
  src/main/java/com/todayhouse/domain/product/exception/SelectionOptionNotFoundException.java
  src/main/java/com/todayhouse/domain/product/exception/StockNotEnoughException.java
  src/main/java/com/todayhouse/domain/user/domain/Seller.java
  src/main/java/com/todayhouse/domain/user/dto/request/FollowRequest.java
  src/main/java/com/todayhouse/domain/user/dto/request/SellerRequest.java
  src/main/java/com/todayhouse/domain/user/dto/response/SellerResponse.java
  src/main/java/com/todayhouse/global/config/WebSecurityConfig.java
  src/main/java/com/todayhouse/global/error/BaseResponseStatus.java
  src/main/java/com/todayhouse/global/error/GlobalExControllerAdvice.java
  src/main/java/com/todayhouse/infra/S3Storage/service/FileServiceImpl.java
  src/test/java/com/todayhouse/domain/product/api/OptionControllerTest.java
  src/test/java/com/todayhouse/domain/product/api/ProductControllerTest.java
  src/test/java/com/todayhouse/domain/product/application/ProductServiceImplTest.java
  src/test/java/com/todayhouse/domain/product/dao/OptionRepositoryTest.java
  src/test/java/com/todayhouse/domain/product/dao/ProductRepositoryTest.java
  src/test/java/com/todayhouse/domain/user/api/SellerControllerTest.java
Labels: 🕹 기능

#51 Product, Seller 관련 오류 수정
  src/main/java/com/todayhouse/domain/product/dto/response/ProductResponse.java
  src/main/java/com/todayhouse/domain/user/application/SellerServiceImpl.java
  src/main/java/com/todayhouse/domain/user/dao/UserRepository.java
  src/test/java/com/todayhouse/domain/user/api/SellerControllerTest.java
  src/test/java/com/todayhouse/domain/user/dao/UserRepositoryTest.java
Labels: 🐛 버그

#57 :sparkles: story detail json에 대한 수정 (#56)
  src/main/java/com/todayhouse/domain/story/application/StoryServiceImpl.java
  src/main/java/com/todayhouse/domain/story/dao/StoryRepository.java
  src/main/java/com/todayhouse/domain/story/dto/response/StoryGetDetailResponse.java
Labels: :hammer_and_wrench: 리팩토링

#58 Product 필터링 기능 구현
  src/main/java/com/todayhouse/domain/category/api/CategoryController.java
  src/main/java/com/todayhouse/domain/category/application/CategoryService.java
  src/main/java/com/todayhouse/domain/category/application/CategoryServiceImpl.java
  src/main/java/com/todayhouse/domain/category/dao/CategoryRepository.java
  src/main/java/com/todayhouse/domain/category/domain/Category.java
  src/main/java/com/todayhouse/domain/category/dto/response/CategoryResponse.java
  src/main/java/com/todayhouse/domain/product/api/OptionController.java
  src/main/java/com/todayhouse/domain/product/api/ProductController.java
  src/main/java/com/todayhouse/domain/product/application/ProductServiceImpl.java
  src/main/java/com/todayhouse/domain/product/dao/ProductRepositoryImpl.java
  src/main/java/com/todayhouse/domain/product/domain/ChildOption.java
  src/main/java/com/todayhouse/domain/product/domain/Product.java
  src/main/java/com/todayhouse/domain/product/dto/request/ProductSearchRequest.java
  src/main/java/com/todayhouse/global/config/WebSecurityConfig.java
  src/test/java/com/todayhouse/domain/category/api/CategoryControllerTest.java
  src/test/java/com/todayhouse/domain/category/application/CategoryServiceImplTest.java
  src/test/java/com/todayhouse/domain/category/dao/CategoryRepositoryTest.java
  src/test/java/com/todayhouse/domain/product/api/OptionControllerTest.java
  src/test/java/com/todayhouse/domain/product/api/ProductControllerTest.java
  src/test/java/com/todayhouse/domain/product/dao/ProductRepositoryTest.java
Labels: 🕹 기능
